name: iexec
version: git
summary: Interactive 'exec' command for kubectl
description: >
  iexec is an interactive filter and selection tool for the kubectl 'exec' command.

  Usage:
    iexec [pod-filter] [command to run inside pod]

  Example:
    # this will open a shell into the selected nginx pod and open a bash prompt
    iexec nginx /bin/bash

confinement: devmode
base: core18
parts:
  iexec:
    plugin: go-local
    go-importpath: github.com/gabeduke/kubectl-iexec
    source: .
    source-type: git
    build-packages:
      - gcc
apps:
  iexec:
    command: bin/kubectl-iexec