name: kubectl-iexec
base: core18
version: '1.9.0'
summary: Kubernetes plugin to interactively exec to a pod
description: |
  Kubectl-iexec is a plugin providing an interactive selector to exec into a running pod. For a search filter,
  the plugin will return a list of pods and containers that match, then perform a kubectl exec to the selection.

grade: stable
confinement: classic

parts:
  kubect-iexec:
    plugin: go
    go-importpath: github.com/gabeduke/kubectl-iexec
    source: .
    source-type: git
