name: Bump Version

on:
  push:
    branches:
      - main

jobs:
  bump_version:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21

    - name: Run Go script
      run: go run hack/bump_version.go -dry-run false

    - name: Push tags
      run: git push --tags
